// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/library.proto

package library

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_UserType int32

const (
	User_GARBAGE        User_UserType = 0
	User_Student        User_UserType = 1
	User_Administration User_UserType = 2
	User_Faculty        User_UserType = 3
)

var User_UserType_name = map[int32]string{
	0: "GARBAGE",
	1: "Student",
	2: "Administration",
	3: "Faculty",
}

var User_UserType_value = map[string]int32{
	"GARBAGE":        0,
	"Student":        1,
	"Administration": 2,
	"Faculty":        3,
}

func (x User_UserType) String() string {
	return proto.EnumName(User_UserType_name, int32(x))
}

func (User_UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{3, 0}
}

// the library
type Library struct {
	Books                *Books   `protobuf:"bytes,1,opt,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Library) Reset()         { *m = Library{} }
func (m *Library) String() string { return proto.CompactTextString(m) }
func (*Library) ProtoMessage()    {}
func (*Library) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{0}
}

func (m *Library) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Library.Unmarshal(m, b)
}
func (m *Library) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Library.Marshal(b, m, deterministic)
}
func (m *Library) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Library.Merge(m, src)
}
func (m *Library) XXX_Size() int {
	return xxx_messageInfo_Library.Size(m)
}
func (m *Library) XXX_DiscardUnknown() {
	xxx_messageInfo_Library.DiscardUnknown(m)
}

var xxx_messageInfo_Library proto.InternalMessageInfo

func (m *Library) GetBooks() *Books {
	if m != nil {
		return m.Books
	}
	return nil
}

type Books struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Books) Reset()         { *m = Books{} }
func (m *Books) String() string { return proto.CompactTextString(m) }
func (*Books) ProtoMessage()    {}
func (*Books) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{1}
}

func (m *Books) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Books.Unmarshal(m, b)
}
func (m *Books) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Books.Marshal(b, m, deterministic)
}
func (m *Books) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Books.Merge(m, src)
}
func (m *Books) XXX_Size() int {
	return xxx_messageInfo_Books.Size(m)
}
func (m *Books) XXX_DiscardUnknown() {
	xxx_messageInfo_Books.DiscardUnknown(m)
}

var xxx_messageInfo_Books proto.InternalMessageInfo

func (m *Books) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

// metadata about a book
type Book struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Isbn                 string   `protobuf:"bytes,3,opt,name=isbn,proto3" json:"isbn,omitempty"`
	NoOfCopies           int32    `protobuf:"varint,5,opt,name=no_of_copies,json=noOfCopies,proto3" json:"no_of_copies,omitempty"`
	AccessLevel          int32    `protobuf:"varint,6,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{2}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *Book) GetNoOfCopies() int32 {
	if m != nil {
		return m.NoOfCopies
	}
	return 0
}

func (m *Book) GetAccessLevel() int32 {
	if m != nil {
		return m.AccessLevel
	}
	return 0
}

// details about a user
type User struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IdNo                 int32         `protobuf:"varint,2,opt,name=id_no,json=idNo,proto3" json:"id_no,omitempty"`
	UserType             User_UserType `protobuf:"varint,4,opt,name=user_type,json=userType,proto3,enum=library.User_UserType" json:"user_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetIdNo() int32 {
	if m != nil {
		return m.IdNo
	}
	return 0
}

func (m *User) GetUserType() User_UserType {
	if m != nil {
		return m.UserType
	}
	return User_GARBAGE
}

type QueryFormat struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryFormat) Reset()         { *m = QueryFormat{} }
func (m *QueryFormat) String() string { return proto.CompactTextString(m) }
func (*QueryFormat) ProtoMessage()    {}
func (*QueryFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{4}
}

func (m *QueryFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryFormat.Unmarshal(m, b)
}
func (m *QueryFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryFormat.Marshal(b, m, deterministic)
}
func (m *QueryFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFormat.Merge(m, src)
}
func (m *QueryFormat) XXX_Size() int {
	return xxx_messageInfo_QueryFormat.Size(m)
}
func (m *QueryFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFormat.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFormat proto.InternalMessageInfo

func (m *QueryFormat) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *QueryFormat) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Response struct {
	Action  string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Status  int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Response_Book
	//	*Response_UserData
	Value                isResponse_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type isResponse_Value interface {
	isResponse_Value()
}

type Response_Book struct {
	Book *Book `protobuf:"bytes,4,opt,name=book,proto3,oneof"`
}

type Response_UserData struct {
	UserData *User `protobuf:"bytes,5,opt,name=user_data,json=userData,proto3,oneof"`
}

func (*Response_Book) isResponse_Value() {}

func (*Response_UserData) isResponse_Value() {}

func (m *Response) GetValue() isResponse_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Response) GetBook() *Book {
	if x, ok := m.GetValue().(*Response_Book); ok {
		return x.Book
	}
	return nil
}

func (m *Response) GetUserData() *User {
	if x, ok := m.GetValue().(*Response_UserData); ok {
		return x.UserData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Book)(nil),
		(*Response_UserData)(nil),
	}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("library.User_UserType", User_UserType_name, User_UserType_value)
	proto.RegisterType((*Library)(nil), "library.Library")
	proto.RegisterType((*Books)(nil), "library.Books")
	proto.RegisterType((*Book)(nil), "library.Book")
	proto.RegisterType((*User)(nil), "library.User")
	proto.RegisterType((*QueryFormat)(nil), "library.QueryFormat")
	proto.RegisterType((*Response)(nil), "library.Response")
	proto.RegisterType((*Empty)(nil), "library.Empty")
}

func init() { proto.RegisterFile("api/library.proto", fileDescriptor_23dfc8515c58d0b2) }

var fileDescriptor_23dfc8515c58d0b2 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x5d, 0xd6, 0xa4, 0xe9, 0xbe, 0x74, 0xa5, 0xf3, 0x46, 0x15, 0x4d, 0x1c, 0x3a, 0x8f, 0x43,
	0x35, 0x4d, 0x8b, 0xd4, 0xdd, 0x76, 0x6b, 0xa1, 0xeb, 0x24, 0x0a, 0x88, 0x14, 0xce, 0x95, 0x9b,
	0x78, 0x9d, 0x45, 0x1a, 0x47, 0xb1, 0x53, 0x29, 0x57, 0xee, 0x9c, 0xf8, 0x19, 0x5c, 0xf8, 0x2f,
	0xfc, 0x05, 0xfe, 0x02, 0x77, 0x64, 0xc7, 0x29, 0xa3, 0xda, 0x85, 0x4b, 0xe5, 0xf7, 0xfc, 0xf2,
	0xf2, 0xf2, 0xbe, 0xaf, 0x70, 0x44, 0x32, 0x16, 0x24, 0x6c, 0x99, 0x93, 0xbc, 0xbc, 0xca, 0x72,
	0x2e, 0x39, 0x72, 0x0d, 0x3c, 0x7d, 0xb1, 0xe2, 0x7c, 0x95, 0xd0, 0x40, 0x49, 0x48, 0x9a, 0x72,
	0x49, 0x24, 0xe3, 0xa9, 0xa8, 0x64, 0x38, 0x00, 0x77, 0x56, 0x09, 0xd1, 0x4b, 0x70, 0x96, 0x9c,
	0x7f, 0x16, 0xbe, 0xd5, 0xb7, 0x06, 0xde, 0xb0, 0x73, 0x55, 0x1b, 0x8e, 0x15, 0x1b, 0x56, 0x97,
	0xf8, 0x12, 0x1c, 0x8d, 0xd1, 0xf9, 0x5f, 0x79, 0x63, 0xe0, 0x0d, 0x0f, 0xff, 0x91, 0xd7, 0xea,
	0xaf, 0x16, 0xd8, 0x0a, 0xa3, 0x13, 0x70, 0x24, 0x93, 0x09, 0xd5, 0xe6, 0x07, 0x61, 0x05, 0x50,
	0x0f, 0x9a, 0xa4, 0x90, 0x0f, 0x3c, 0xf7, 0xf7, 0x35, 0x6d, 0x10, 0x42, 0x60, 0x33, 0xb1, 0x4c,
	0xfd, 0x86, 0x66, 0xf5, 0x19, 0xf5, 0xa1, 0x9d, 0xf2, 0x05, 0xbf, 0x5f, 0x44, 0x3c, 0x63, 0x54,
	0xf8, 0x4e, 0xdf, 0x1a, 0x38, 0x21, 0xa4, 0xfc, 0xfd, 0xfd, 0x2b, 0xcd, 0xa0, 0x33, 0x68, 0x93,
	0x28, 0xa2, 0x42, 0x2c, 0x12, 0xba, 0xa1, 0x89, 0xdf, 0xd4, 0x0a, 0xaf, 0xe2, 0x66, 0x8a, 0xc2,
	0xdf, 0x2d, 0xb0, 0x3f, 0x09, 0xaa, 0xdf, 0x90, 0x92, 0x75, 0x1d, 0x47, 0x9f, 0xd1, 0x31, 0x38,
	0x2c, 0x5e, 0xa4, 0x5c, 0x87, 0x71, 0x42, 0x9b, 0xc5, 0xef, 0x38, 0xba, 0x86, 0x83, 0x42, 0xd0,
	0x7c, 0x21, 0xcb, 0x8c, 0xfa, 0x76, 0xdf, 0x1a, 0x74, 0x86, 0xbd, 0xed, 0xa7, 0x2a, 0x2b, 0xfd,
	0xf3, 0xb1, 0xcc, 0x68, 0xd8, 0x2a, 0xcc, 0x09, 0x4f, 0xa0, 0x55, 0xb3, 0xc8, 0x03, 0x77, 0x3a,
	0x0a, 0xc7, 0xa3, 0xe9, 0xa4, 0xbb, 0xa7, 0xc0, 0x5c, 0x16, 0x31, 0x4d, 0x65, 0xd7, 0x42, 0x08,
	0x3a, 0xa3, 0x78, 0xcd, 0x52, 0x26, 0x64, 0xae, 0x87, 0xd2, 0xdd, 0x57, 0x82, 0x5b, 0x12, 0x15,
	0x89, 0x2c, 0xbb, 0x0d, 0x3c, 0x07, 0xef, 0x43, 0x41, 0xf3, 0xf2, 0x96, 0xe7, 0x6b, 0x22, 0xd1,
	0x19, 0xd8, 0xaa, 0x55, 0x33, 0x9f, 0x9d, 0xc2, 0xf5, 0x95, 0x92, 0xa8, 0x10, 0xfa, 0x0b, 0x1e,
	0x4b, 0x54, 0x9a, 0x50, 0x5f, 0xe1, 0x1f, 0x16, 0xb4, 0x42, 0x2a, 0x32, 0x9e, 0x8a, 0x6a, 0x00,
	0x91, 0x7a, 0xb5, 0x29, 0xc2, 0x20, 0xc5, 0x0b, 0x49, 0x64, 0x21, 0x4c, 0x17, 0x06, 0x21, 0x1f,
	0xdc, 0x35, 0x15, 0x82, 0xac, 0xa8, 0x99, 0x4d, 0x0d, 0xd1, 0xb9, 0x09, 0x67, 0x3f, 0x11, 0xee,
	0x6e, 0xcf, 0xc4, 0xbb, 0x34, 0x65, 0xc6, 0x44, 0x12, 0x3d, 0xc0, 0xdd, 0x8c, 0x77, 0x7b, 0x55,
	0x8b, 0xaf, 0x89, 0x24, 0x63, 0x17, 0x9c, 0x0d, 0x49, 0x0a, 0x8a, 0x5d, 0x70, 0x26, 0xeb, 0x4c,
	0x96, 0xc3, 0xdf, 0x16, 0x74, 0xcc, 0xba, 0xce, 0x69, 0xbe, 0x61, 0x11, 0x45, 0x6f, 0xa0, 0x3d,
	0x63, 0x42, 0x8e, 0x92, 0xa4, 0x5a, 0xcb, 0x93, 0xad, 0xdf, 0xa3, 0xea, 0x4e, 0x77, 0x96, 0x19,
	0x3f, 0xff, 0xf2, 0xf3, 0xd7, 0xb7, 0xfd, 0x67, 0x18, 0x82, 0x84, 0x09, 0xa9, 0xb9, 0x1b, 0xeb,
	0x02, 0x4d, 0xc1, 0x1d, 0xc5, 0x71, 0xb5, 0xb0, 0x4f, 0xfa, 0x1c, 0x6d, 0xd9, 0xba, 0x42, 0x7c,
	0xac, 0xad, 0x0e, 0x71, 0x2b, 0x20, 0xd5, 0xa3, 0xca, 0xe8, 0x2d, 0xc0, 0x9c, 0x92, 0x3c, 0x7a,
	0xf8, 0x3f, 0xaf, 0x9e, 0xf6, 0xea, 0x62, 0x2f, 0x10, 0xdb, 0xa7, 0x6f, 0xac, 0x8b, 0x65, 0x53,
	0xff, 0x59, 0xaf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x55, 0x7d, 0x45, 0x8a, 0xe8, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LibraryServiceClient is the client API for LibraryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LibraryServiceClient interface {
	ListAllBooks(ctx context.Context, in *QueryFormat, opts ...grpc.CallOption) (*Books, error)
	AddBook(ctx context.Context, in *QueryFormat, opts ...grpc.CallOption) (*Response, error)
	SearchBook(ctx context.Context, in *QueryFormat, opts ...grpc.CallOption) (*Response, error)
}

type libraryServiceClient struct {
	cc *grpc.ClientConn
}

func NewLibraryServiceClient(cc *grpc.ClientConn) LibraryServiceClient {
	return &libraryServiceClient{cc}
}

func (c *libraryServiceClient) ListAllBooks(ctx context.Context, in *QueryFormat, opts ...grpc.CallOption) (*Books, error) {
	out := new(Books)
	err := c.cc.Invoke(ctx, "/library.LibraryService/ListAllBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) AddBook(ctx context.Context, in *QueryFormat, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/library.LibraryService/AddBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) SearchBook(ctx context.Context, in *QueryFormat, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/library.LibraryService/SearchBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibraryServiceServer is the server API for LibraryService service.
type LibraryServiceServer interface {
	ListAllBooks(context.Context, *QueryFormat) (*Books, error)
	AddBook(context.Context, *QueryFormat) (*Response, error)
	SearchBook(context.Context, *QueryFormat) (*Response, error)
}

func RegisterLibraryServiceServer(s *grpc.Server, srv LibraryServiceServer) {
	s.RegisterService(&_LibraryService_serviceDesc, srv)
}

func _LibraryService_ListAllBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFormat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).ListAllBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.LibraryService/ListAllBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).ListAllBooks(ctx, req.(*QueryFormat))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFormat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.LibraryService/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).AddBook(ctx, req.(*QueryFormat))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_SearchBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFormat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).SearchBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.LibraryService/SearchBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).SearchBook(ctx, req.(*QueryFormat))
	}
	return interceptor(ctx, in, info, handler)
}

var _LibraryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "library.LibraryService",
	HandlerType: (*LibraryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAllBooks",
			Handler:    _LibraryService_ListAllBooks_Handler,
		},
		{
			MethodName: "AddBook",
			Handler:    _LibraryService_AddBook_Handler,
		},
		{
			MethodName: "SearchBook",
			Handler:    _LibraryService_SearchBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/library.proto",
}
